services:
  - type: web
	name: capoeira-bot
	runtime: python
	env: python-3.12.8
	buildCommand: pip install -r requirements.txt
	startCommand: python bot.py
	envVars:
	  - key: BOT_TOKEN
		sync: false